### ISSUE TITLE
Missing factors_summary tool

### ISSUE THREAD

**Issue by djson8** [phnmnl/container-galaxy-k8s-runtime#134]
Looks like  `factors_summary` tool that generates some JSON that is a factors summary of a ISA-Tab study has gone missing. Maybe accidentally removed during the tools reorgranization.

**Comment by pcm32** [comment]
File is being references in tool_conf.xml here:
https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/66fe5229d07e7eda87b90516556b79a70542025b/config/tool_conf.xml#L90

however, when the files were moved around, apparently someone copied the contents of tool `tool id="isa_get_study_factors" name="Get study factors"` into the get factors summary file:

https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/release/v17.09-pheno-cerebellin/tools/phenomenal/isatools/isa_get_factors_summary.xml

So we need to fix the content of that file and it should work again.

**Comment by djcomlab** [comment]
Have also added a fix in https://github.com/phnmnl/container-galaxy-k8s-runtime/tree/isa_updates_for_cerebellin

**Comment by djcomlab** [comment]
Fixed in PR #146
