### ISSUE TITLE
Get values of study factors produces empty result for MTBLS36 - Cultivars

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#141]
http://193.62.52.92:30700/?tool_id=isa_get_study_factor_values&version=1.0&__identifer=kc3n4l0zeoh

Produces an empty json file when run with MTBLS36 and factor name "Cultivars". The value cultivars was obtained from Get study factors tool. Ping @djcomlab 

Pod logs look like:

```
INFO:root:Getting values for factor /export/galaxy-central/database/files/000/dataset_470.dat in study MTBLS36. Writing to Cultivars.
INFO:isatools.net.mtbls:Setting up ftp with ftp.ebi.ac.uk
INFO:isatools.net.mtbls:Logging in as anonymous user...
INFO:isatools.net.mtbls:Log in successful!
INFO:isatools.net.mtbls:Looking for study 'MTBLS36'
INFO:isatools.net.mtbls:Using directory '/tmp/tmphbls_ajy'
INFO:isatools.net.mtbls:Retrieving file 'ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS36/i_Investigation.txt'
INFO:isatools.net.mtbls:Retrieving file 'ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS36/s_ESB Tomato.txt'
INFO:isatools.net.mtbls:Retrieving file 'ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS36/a_esb tomato_metabolite profiling_mass spectrometry-1.txt'
INFO:isatools.net.mtbls:Retrieving file 'ftp.ebi.ac.uk/pub/databases/metabolights/studies/public/MTBLS36/a_esb tomato_metabolite profiling_mass spectrometry.txt'
```

The job doesn't show as failed, but output is empty.

**Comment by pcm32** [comment]
Interestingly, if I get the cultivars values from MetaboLights Factors Viz and use then CNR as value with MTBLS36 and Cultivars, I get a list of file names.

**Comment by djcomlab** [comment]
I'm surprised the output is empty, I would expect an empty list normally.

There seems to be a problem with these tools anyway, for some reason the latest on publicdev also does not behave properly. I'm updating them anyway right now so will check them again.

**Comment by djcomlab** [comment]
This is a problem with the tools and how the run_mtblisa.py script is called. I've pushed a fix.

Although I'm surprised that the value "Cultivars" was got from the "Get study factors tool" as when I tried it most recently on the public instance it completely didn't work...
