### ISSUE TITLE
Weird initial text in Metfrag tour

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#153]
When starting the tour, you can see the following text, which doesn't make sense:

> This annotation is based on the mapping of in silico generated fragments to the experimental spectra and scoring of your arrow keys and leave the tour at any time point with 'Escape' or the 'End tour' button.

Maybe the whole text is to long to be rendered?

@sneumann @c-ruttkies

**Comment by ilveroluca** [comment]
This has been fixed.
