### ISSUE TITLE
NMR Workflow disappeared from list of shared workflows

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#170]
For some reason the NMR workflow doesn't show up as part of the list of shared workflows.

**Comment by sneumann** [comment]
I have seen it now on a fresh kubenow with the new community 17.09 setup:
http://galaxy.129.70.51.51.nip.io/u/admin/w/metabolomics-nmr-rnmr1d-metabolights-data-processing-and-plot
So once we have a second confirmation, this can be closed. Yours, Steffen

**Comment by ilveroluca** [comment]
I confirmed that it's included in the current deployment.
