### ISSUE TITLE
Wrong value string passed to PeakPickerHires option

### ISSUE THREAD

**Issue by sneumann** [phnmnl/container-galaxy-k8s-runtime#177]
Hi,
in https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/abcda7f2efd895f1ca7bbf30606e5d838753d211/tools/phenomenal/ms/OpenMS/PeakPickerHiRes.xml#L123

is the `value="relative(ppm)"` but the PeakPickerHires expects just `relative`. 
@PayamEmami , can you check my imminent PR ? Also, was this manually created, 
or automatically through CTD, in that case there might be other cases lurking elsewhere.

Yours, Steffen

**Comment by PayamEmami** [comment]
Hello,
It depends on the OpenMS version. But in general relative should work fine. 

Sorry for late reply. It was automatically created. We still have similar problems with other tools like featureFinderMetabo.
I guess CTD converter should be changed a bit and we need a test for many of the tools. 

Best,
Payam
