### ISSUE TITLE
Wiki link is weird

### ISSUE THREAD

**Issue by hsiaoyi0504** [phnmnl/container-galaxy-k8s-runtime#192]
When I clicked the wiki page of this repo, it will redirected to home page of this repo. I doubted it's one of the settings of this repo.

**Comment by sneumann** [comment]
The repo here does not really have a wiki, 
instead the master-wiki is in https://github.com/phnmnl/phenomenal-h2020/wiki
I have now disabled the wiki link here to avoid confusion. Yours, Steffen
