### ISSUE TITLE
mzML data type not immediately recognised in a fresh installation

### ISSUE THREAD

**Issue by sneumann** [phnmnl/container-galaxy-k8s-runtime#205]
Hi, on a freshly installed instance based on 17.09 galaxy-stable, I upload an mzML file
(detect datatype=auto), the metadata says it is format mzml, but the xcms tool (and iirc also OpenMS) 
don't recognize that as valid input. Then I edit and change the datatype 
from mzml to mzml (sic!) and things work. Any mzML from the same experiment 
uploaded afterwards is available for xcms right away.
My suspicion would be that the mzML is not correctly attached to the history item, 
that could be a Galaxy issue. Let's re-visit once we are on 18.01.
Yours, Steffen

**Comment by ilveroluca** [comment]
This issue seems to be solved with the updated version of Galaxy we're deploying with Dalcotidine.  I just verified that it works on minikube with the "IPO for xcmsSet" tool using our current (almost RC2) PhenoMeNal deployment.

Closing the issue.
