### ISSUE TITLE
Reference to undefined `raw` data format

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/container-galaxy-k8s-runtime#213]
The `phenomenal/ms/dimspy/process_scans.xml` wrapper is referencing a data format/extension called `raw` that isn't defined in Galaxy.  The start-up logs show this warning:

```
galaxy.tools.parameters.basic WARNING 2018-06-20 17:40:17,617 Datatype class not found for extension 'raw', which is used in the 'format' attribute of parameter 'source'
```

The references are on lines 94 and 99 of the wrapper file.

**Comment by jbradbury** [comment]
@ilveroluca as far as I am aware (I am no expert with dimspy) raw files from some manufacturers can be used with dimspy process scans

**Comment by jbradbury** [comment]
@ilveroluca on Galaxy the data type is called thermo.raw

**Comment by ilveroluca** [comment]
Then PR #286 should be good for approval.  It removes the reference to `raw` while leaving unchanged the references to `thermo.raw` and `mzml`.
