### ISSUE TITLE
Requesting new password for Galaxy

### ISSUE THREAD

**Issue by namratakale** [phnmnl/container-galaxy-k8s-runtime#240]
on raising request for 'forgot password', failed to receive any email. Also the statement on the page 'Your reset request for namrata@bi.ac.uk has been received. Please check your email account for more instructions. If you do not receive an email shortly, please contact an administrator' needs link to 'administrator

**Comment by ilveroluca** [comment]
Hi @namratakale.  Was this on https://public.phenomenal-h2020.eu/?

**Comment by namratakale** [comment]
Hi @ilveroluca yes

**Comment by ilveroluca** [comment]
I presume the original message said `namrata@ebi.ac.uk` and not `namrata@bi.ac.uk` :-)

**Comment by pcm32** [comment]
This seems to me like an OSI Layer 8 ;-) type of problem, which means that this issue should be closed.
