### ISSUE TITLE
Make workflows shared to all users by default

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#26]
Currently API injected workflows are only initially visible to the admin users, and they don't appear in the shared workflows part. Workflow injection should handle as well that workflows are immediately published/shared.

@ilveroluca do you know if bioblend caters for this? Or we need to push this issue upstream there (the availability of the functionality).

**Comment by ilveroluca** [comment]
At the moment it's not implemented in Galaxy:  https://github.com/galaxyproject/galaxy/issues/1842

We need to look into implementing it ourselves

**Comment by pcm32** [comment]
Workflows are now shared to all users (not to their own lists, but to the commonly shared space). Should we close this then @ilveroluca ? I think that solution is sufficiently good at the moment.

**Comment by ilveroluca** [comment]
+1
