### ISSUE TITLE
ISA-Tab Viewer plugin does not load

### ISSUE THREAD

**Issue by djcomlab** [phnmnl/container-galaxy-k8s-runtime#282]
I've just noticed that the ISA-Tab Viewer visualization plugin is not present in RC1 publicdev.

The changes that were pulled in https://github.com/phnmnl/container-galaxy-k8s-runtime/pull/250/ included adding some COPY lines to the root `Dockerfile` (I tested by building this way and it worked fine), but I presume the image building for the releases does not build using this `Dockerfile` and the visualization plugin needs to be copied into the image elsewhere.

**Comment by ilveroluca** [comment]
Fixed by PR #285
