### ISSUE TITLE
ISA get data files from JSON gives empty list for MTBLS36

### ISSUE THREAD

**Issue by sneumann** [phnmnl/container-galaxy-k8s-runtime#293]
Hi @djcomlab ,
if I download MTBLS36 (Metadata only), and then use 
https://publicdev.phenomenal-h2020.eu/?tool_id=isa_get_data_files_list 
on this ISA history item, I get an empty list of data files. 
Yours, Steffen

**Comment by djcomlab** [comment]
Removing this tool in favour of `ISAslicer2`.
