### ISSUE TITLE
Adding datatype for nmrML

### ISSUE THREAD

**Issue by korseby** [phnmnl/container-galaxy-k8s-runtime#37]
Hi @pcm32 @rsalek @DSchober @sneumann @c-ruttkies  ,

There is a datatype missing for nmrML files.

Is it enough to add an entry to config/datatypes_conf.xml ?

```
<datatype extension="nmrml" type="galaxy.datatypes.metabolomics:nmrML" mimetype="application/xml" display_in_upload="true"/>
```

Best wishes, *Kristian

**Comment by pcm32** [comment]
I presume that this is resolved by now. Can we close this? Thanks!
