### ISSUE TITLE
Preserve file names in Galaxy

### ISSUE THREAD

**Issue by korseby** [phnmnl/container-galaxy-k8s-runtime#44]
Hi all,

A typical Metabolomics study consists of lots of source files with raw data. These source file names (samples or “sourceFileName”) are referenced in the ISA-Tab and are e.g. needed in order to perform grouping with factors in XCMS. Without knowing the filename an assignment to the particular sample or the factor (e.g. control / disease) is not possible.

However, Galaxy automatically renames the files to `dataset_xxx.dat` and there is currently no way to know what the name of the originating file was.

In order to correctly process metabolomics data, we need to preserve the file names of the mzML / nmrML / netcdf source files. How can we accomplish that Galaxy preserves the names of the files from one tool to the next?

Example:

- mtbls_nmr_raw_dummy_importer:
	- Downloads MTBLS1.zip study
	- Moves all the zip-files to the output directory which points towards a Galaxy dataset collection
	- In the Galaxy history, the collection contains the individual zip files and each dataset inside the collection still has the correct name

- next tool:
	- will get either an individual file or all the files of the collection, but they are named to something like database/files/000/dataset_273.dat

@sneumann , @c-ruttkies , @PayamEmami , @pcm32 , @pierrickrogermele

**Comment by PayamEmami** [comment]
Hello,
We can configure output name to be identical to the input using configure output section (click on a tool in the workflow you will have the option in the right menu). Setting it to #{input_name} will result in identical output name (not extension) as we have in input.

This is of course can make it difficult for the users but currently this is the easiest option.

Best,
Payam

**Comment by PayamEmami** [comment]
Sorry i was on the phone so could not write more. 
basically, the usage should be #{input_name} where input_name is the data input parameter for that specific tool. For example for OpenMS FileFilter, "param_in" is the input parameter. So we need to set #{param_in} . If the input name is for example sampleName.mzML, this will result in Galaxy15-[sampleName].mzML. 
Best,
Payam

**Comment by korseby** [comment]
Hi @PayamEmami 

I had a look at your FileFilter example. However, I probably do not understand you correctly:

https://github.com/phnmnl/container-nmrmlconv/commit/0c393735a82aee2ff73626397e116c2bea02dec2

Instead of `$infile` containing the `dataset_xxx.dat`, the script just contains `#{infile}` and does nothing.

Can you attach a diff?

It will be 35°C hot here today... Best wishes :)

**Comment by PayamEmami** [comment]
Oh. i knew i'm bad at describing things!
You don't need to change anything in the docker files. You should change the workflow settings in Galaxy for every node.
I just made a small video on that. 
https://youtu.be/dRE2W7k7iCo

Best,
Payam

**Comment by korseby** [comment]
Hi @PayamEmami 

Ok. Now I understand you. :)

If you connect another tool to the output of FileFilter. Will it get the correct file name?

Best wishes

**Comment by PayamEmami** [comment]
Yes. But you do the same thing for that tool as well. for example i did for FileFilter->featureFinderMetabo and the result was Galaxy47-[ID1.mzML].featurexml . as expected.

35! really ?! I'm always jealous of you guys. We are almost preparing for winter. 
Best,
Payam

**Comment by korseby** [comment]
I still can't get it to work as I need it to. 

Ok. This is my tool-xml (https://github.com/phnmnl/container-nmrmlconv/blob/develop/galaxy/nmrmlconv.xml):

```
<?xml version='1.0' encoding='UTF-8'?>
<!--Proposed Tool Section: [File Handling]-->
<tool id="nmrmlconv" name="nmrmlconv" version="0.2">
  <requirements>
    <container type="docker">container-registry.phenomenal-h2020.eu/phnmnl/nmrmlconv</container>
  </requirements>
  <description>Converts vendor RAW NMR to nmrML.</description>
  <command><![CDATA[
    echo $infile;
    ls -R -al $infile;
    mkdir -p \$PWD/tmp;
    unzip -q -d \$PWD/tmp $infile;
    ls -al \$PWD/tmp;
    export samplename="ADG10003u_007";
    java -jar /usr/local/share/nmrML/converter.jar -l create -b -z -t $venformat -a \$samplename -i \$PWD/tmp -o $outfile;
  ]]>
  </command>
  <inputs>
    <param name="infile" type="data" format="zip" optional="False" label="Input file in zip format to convert" />
    <param name="venformat" type="select" value="Bruker" optional="True" label="Vendor format" help="See below.">
      <option value="bruker" selected="True">Bruker</option>
      <option value="varian">Varian</option>
      <option value="jeol">Jeol</option>
      <option value="tecmag">TecMag</option>
      <option value="nmrstar">NMR Star</option>
      <option value="chemmagnetics">ChemMagnetics</option>
      <option value="geomega">GE Omega</option>
      <option value="galactic">Galactic</option>
      <option value="jcamp">JCAMP</option>
      <option value="lybrics">Lybrics</option>
      <option value="nuts">Nuts</option>
      <option value="nicolet">Nicolet</option>
      <option value="netcdf">netCDF</option>
    </param>
  </inputs>
  <outputs>
    <data name="outfile" type="data" format="nmrML" label="nmrML file" />
  </outputs>
  <help>
nmrML is an open mark-up language for NMR data. This tool converts RAW vendor NMR data to nmrML format.
  </help>
</tool>
```

Please have a look at the `<command><![CDATA[` part. There I do a simple `echo $infile`. It reveals that, **inside** the tool, the file is named `dataset_xxx.dat`. Outside the tool in Galaxy the file is named correctly to something like `ADG_xxxxxxx.zip` and I am able to manually save it under that name. But inside the running tool, the file is always renamed!

How can I bring the tool inside Galaxy to get the full filename?

**Comment by PayamEmami** [comment]
The problem is more complex than I was thinking. This is not controlled by users. So far it seems like there is a parameter in for example :
https://github.com/galaxyproject/galaxy/blob/94fd3a51a2a3a46aa4a834ed6d7d0bb50e6154a5/lib/galaxy/objectstore/__init__.py
the parameter is called “alt_name” which should hopefully overwrite the default dataset name.
I hope we can set this to something dynamic in for example https://galaxyproject.org/object-store/
However, if does not happen it will seriously limit the workflows. 
Best,
Payam

**Comment by PayamEmami** [comment]
An update, 
to get name of the dataset you can use: "$yourInputName.name".
Galaxy internally renames the files to dataset_<INT>.dat . That i cannot do anything for at the moment but you can retrieve what file name it correspond to. Example: 
`<![CDATA[
    echo "Test1:";
	echo $infile;
	echo "Test2:";
	echo $infile.name;
  ]]>`

Output:

`==== Pod galaxy-17-5bgzn log start ====

2017-06-23T20:34:18.287175182Z Test1:
2017-06-23T20:34:18.287317160Z /opt/galaxy_data/files/000/dataset_11.dat
2017-06-23T20:34:18.287351362Z Test2:
2017-06-23T20:34:18.287355311Z testFile.zip


==== Pod galaxy-17`

This won't completely fix the problem but at least the tool will know the real name of the file.
We need to fix this for the collections as well.

Best,
Payam

**Comment by PayamEmami** [comment]
OK. For dataset lists (when you set multiple=True in the input) we can loop through input:
`#for $zip in $infile:
 echo $zip.name
 #end for`

Output:
testFile1.zip echo testFile2.zip

Best,
Payam

**Comment by pcm32** [comment]
I think that the solution could be to generate data set collections of file that respond to a certain (factor1, factor2, .., factorN) =(value1, value2, ..., value3), based on the ISA... this avoids having to keep track of the files through the ISA files and makes naming less of a problem...

That is what I presented in Halle (isa2mzml, isa2nmrml collections, with the previous query). But haven't had time to implement yet.

**Comment by pcm32** [comment]
The idea of that tool is that it interacts with the factors query modules that @djcomlab wrote, so takes as input a json file with all the paths inside the ISA, and downloads them into a data set collection.

**Comment by korseby** [comment]
Hi @PayamEmami 

You are my hero Payam. I'm sorry to say it, but you are only half a genius. 😆 

Using `$infile.name` works greatly for single files. 😄 
Using `$infile.name` does not work for collections. 😭 

Let me explain.

In the xml I define the following input:
```
  <inputs>
    <param name="infiles" type="data" format="nmrML" optional="False" multiple="True" label="Collection data" />
  </inputs>
```

In the CDATA I try to get the shell variables as usual:
```
  <command><![CDATA[
    echo $infiles;
    echo $infiles.name;
```

The line `echo $infiles.name;` results in the following error:
```
Traceback (most recent call last):
  File "/usr/src/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/usr/src/galaxy/lib/galaxy/jobs/__init__.py", line 879, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/usr/src/galaxy/lib/galaxy/tools/evaluation.py", line 454, in build
    raise e
NotFound: cannot find 'name' while searching for 'infiles.name'
```

I tried to adapt your `#for $zip in $infile: echo $zip.name #end for` to shell but can't get it to work. Can you post it in shell syntax?


@pcm32 : Indeed we intend to use ISA. But with collections there is no way we could match the arbitraty galaxy-filenames `dataset_xxx.dat` to a particular entry in the ISA-Tab.

**Comment by PayamEmami** [comment]
Hello, 

I told you i'm bad at describing things. I have developed a node + r code to convert galaxy names to real names and output csv file. 

Please have a look.
I would also like to ask @pcm32 to add another section in galaxy called utilities which some tools like this can be placed there. 

Best,
Payam

[filenameextractor.zip](https://github.com/phnmnl/container-galaxy-k8s-runtime/files/1104651/filenameextractor.zip)

**Comment by korseby** [comment]
Hi all,

with Payams version and a few tweaks I was able to implement a workaround version. I will send a pull request soon. We have to tie ISA-Tab to filenames and factor levels and integrate that into our tools as soon as possible.

By the way, the official API documentation (https://docs.galaxyproject.org/en/latest/dev/schema.html) was not very helpful in that matter.

@PayamEmami You are still my hero. One free beer for you. But only starköl ;)
