### ISSUE TITLE
Organisation of Galaxy tools - Particularly for MS

### ISSUE THREAD

**Issue by rsalek** [phnmnl/container-galaxy-k8s-runtime#75]
Hi All,

I want to restructure the Tools currently displayed in https://public.phenomenal-h2020.eu/ particularly what is under MS. To me, it is a way too long of a shopping list. I need your inputs for classification, @sneumann, @PayamEmami @ethevenot @fabienjourdan @proccaserra  .....

So I propose:
MS-XCMS (All XCMS stuff here)
MS-OpenMS (All OpenMS stuff here).

New categories:
- Annotation
Annotation-MetFrag
Annotation-CAMERA ? or suggstion ....

- Data Conversion
For data format converter tools. 

Move all ISA related stuff to ISATools, some are currently in MS, e.g. mzml2isa

"Post-Processing" and "Stats" better classification. i.e Normalisation step etc under "Post-Processing". Also, STATS look quite empty compared to the demos: 
Can we have W4M-Univariate, ... all under STATS? 

Best,
Reza

**Comment by ethevenot** [comment]
Dear Reza, dear All,

W4M-Univariate, Multivariate, and Biosigner should indeed be gathered in the 'STATS' section.
W4M-lcmsmatching belongs to an LC-MS 'annotation' section.

Kind Regards,

Etienne.

**Comment by rsalek** [comment]
Thank you very much @ethevenot, I would start doing it locally this week.

**Comment by PayamEmami** [comment]
Thank you @rsalek .

Here is my suggestion which is partly based on OpenMS categories: 

*****Utilities*****
xcms-collect-peaks
xcmssplit

*****File Handling*****
DTAExtractor 
FileConverter 
FileFilter 
FileInfo 
FileMerger 
IDMerger 
IDFileConverter 
MapStatistics 
SpectraMerger 
TextExporter 
MzTabExporter 
ms-vfetc
camera-prepareoutput
cameraToFeatureXML
ConsensusXMLToXcms
featureXMLToCAMERA
featureXMLToXcms


*****Signal Processing and Preprocessing*****
BaselineFilter 
InternalCalibration 
MapNormalizer 
MassTraceExtractor 
NoiseFilterGaussian 
NoiseFilterSGolay 
PeakPickerHiRes 
PeakPickerWavelet 
PrecursorMassCorrector 
HighResPrecursorMassCorrector 
Resampler 
SpectraFilterBernNorm 
SpectraFilterMarkerMower 
SpectraFilterNLargest 
SpectraFilterNormalizer 
SpectraFilterParentPeakMower 
SpectraFilterScaler 
SpectraFilterSqrtMower 
SpectraFilterThresholdMower 
SpectraFilterWindowMower 
TOFCalibration 
xcms-fill-peaks
xcms-blankfilter
xcms-dilutionfilter

****Quantitation****
AdditiveSeries 
Decharger 
EICExtractor 
FeatureFinderCentroided 
FeatureFinderRaw 
FeatureFinderIsotopeWavelet 
FeatureFinderMetabo 
FeatureFinderMRM 
ITRAQAnalyzer 
ProteinQuantifier 
SILACAnalyzer 
SeedListGenerator 
xcms-find-peaks

*****Map Alignment*****
ConsensusMapNormalizer 
MapAlignerIdentification 
MapAlignerPoseClustering 
MapAlignerSpectrum 
MapRTTransformer 
FeatureLinkerLabeled 
FeatureLinkerUnlabeled 
FeatureLinkerUnlabeledQT 
xcms-group-peaks 
xcms-correct-rt 

*****Identification*****
CompNovo 
CompNovoCID 
InspectAdapter 
MascotAdapter 
MascotAdapterOnline 
OMSSAAdapter 
PepNovoAdapter 
XTandemAdapter 
SpecLibSearcher 
camera-annotate-peaks
metfragcli
camera-group-fwhm 
camera-group-corr 
camera-find-isotopes 
camera-find-adducts
map-msms2camera 
msms2metfrag
metfrag-cli-batch 
metfrag-vis 
metfrag-cli-batch-multiple

*****Identification Processing*****
ConsensusID 
FalseDiscoveryRate 
IDConflictResolver 
IDFilter 
IDMapper 
IDPosteriorErrorProbability 
IDRTCalibration 
PeptideIndexer 
ProteinInference 
metfrag-aggregatemetfrag
msnbase-filter-merge-msms
metfrag-passatuttoPEP

*****Targeted Experiments*****
InclusionExclusionListCreator 
PrecursorIonSelector

**Comment by rsalek** [comment]
After talking with @pcm32, in Galaxy, we can try to have two options at the top: 
**Basic:** 
Application-based (e.g MS, NMR, STAT....)
Format:
ToolName-Function-SubF-...
_e.g._ 
**MS-XCMS**
   xcms-group-peaks
**MS-OpenMS**
  FeatureFinderCentroided
  FeatureFinderRaw

**Advance:** 
Then what @PayamEmami suggested but I sill need to make it 
ToolName-Function-SubF-...
e.g. 
**Quantitation**
OpenMS-FeatureFinderCentroided

There would be a lot of overlap tools but better to have both "Basic" and "Advance" options? Any thoughts ...

**Comment by pcm32** [comment]
@rsalek I'm not sure that this would work (basic and advanced), you should try it before having a long discussion here about it. Also, it would be good if you and Rachel write the comments that you had here.

**Comment by proccaserra** [comment]
+1 with @pcm32. All good input and simply by looking at the terms supplied, we have hints about that people want to do. However, by all means, for each of the 'bins' people suggest, can I ask them to *always* provide a textual definition for that bin. It great help clarify things as it forces to put more thoughts it the process.

example: What is the difference between the bin 'identification' and 'identification processing'? what is the purpose of 'identification processing'? and 'Basic what?' and 'advanced what'?

@rsalek as discussed before, it would be a good thing to relate this with curation guidelines in place at Metabolights, we need to integration with existing work and try to avoid fragmentation.

**Comment by rsalek** [comment]
Hello, I made an example, the first attempt below: 
This would be the layout:
<img width="200" alt="screenshot 2017-11-15 11 04 24" src="https://user-images.githubusercontent.com/1385716/32832894-f5f8fae6-c9f4-11e7-962b-914d38744e2c.png">
Also, I have put some tags, don't know how to make use of different colors!
<img width="237" alt="screenshot 2017-11-15 11 04 41" src="https://user-images.githubusercontent.com/1385716/32832893-f5e2f728-c9f4-11e7-9c6e-1dd02160fe27.png">

If you want to browse the details see: 
https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/feature/reorganizeGalaxyTools/config/tool_conf.xml

I will make another one based on @PayamEmami suggestions. 
Let me know what you think ...

**Comment by pcm32** [comment]
This is now sorted as part of cerebellin release, will close this.
