### ISSUE TITLE
Issue when loading MS Start to end workflow

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#76]
@PayamEmami @c-ruttkies excellent work guys on adding finally the monster workflow!! When I tried to load it I got the following warning on Galaxy:

Issues loading this workflow

Please review the following issues, possibly resulting from tool upgrades or changes.
Step 21: metfrag-cli-batch-multiple
No value found for 'Additional MetFrag scores'.

Any ideas? The workflow looks fine though, but I don't have the data to try it. Related to that, it would be nice as well if you guys can come up with a tutorial on how to use this workflow, towards a minor release of galaxy where we include it (where I plan to have the tools with resource limits).

Thanks!

**Comment by PayamEmami** [comment]
Thank you @pcm32
I think the workflow was saved before  the parameter for additional metfrag score existed. 
We can simply open and save it one more time so the parameters will be updated. 
I am also super excited to see how the limit on  resources work. That will actually affect the design of the workflow. 

We are preparing a tutorial on how to analyze MS data and design workflows including choosing correct parameters. 
I will contact you when ready to upload.

**Comment by c-ruttkies** [comment]
Issue was fixed by recreating the workflow.
