### ISSUE TITLE
Configure Galaxy to use multiple web server processes

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/container-galaxy-k8s-runtime#89]
Recent tests have shown that the current Galaxy configuration used within PhenoMeNal results in very high response latency when the deployment is being used intensely (multiple users). We'll try a multiple web server configuration, as described in the Galaxy documentation, to see if it resolves the problem.

Relevant Galaxy docs:  https://galaxyproject.org/admin/config/performance/scaling/

**Comment by pcm32** [comment]
This is now addressed by https://github.com/phnmnl/container-galaxy-k8s-runtime/pull/131. Eventually we could start work to dissect handlers out of the main container and web process to run on their own separately (variable replicate numbers), for a truly scalable experience. Will close for now.
